export const cardList = [
  {
    id: 1,
    theme: "Web Design",
    title: "Название задачи",
    date: "30.10.23",
    colorClass: "_orange",
    status: "Без статуса",
  },
  {
    id: 2,
    theme: "Research",
    title: "Название задачи",
    date: "30.10.23",
    colorClass: "_green",
    status: "Без статуса",
  },
  {
    id: 3,
    theme: "Web Design",
    title: "Название задачи",
    date: "30.10.23",
    colorClass: "_orange",
    status: "Без статуса",
  },
  {
    id: 4,
    theme: "Copywriting",
    title: "Название задачи",
    date: "30.10.23",
    colorClass: "_purple",
    status: "Без статуса",
  },
  {
    id: 5,
    theme: "Research",
    title: "Название задачи",
    date: "30.10.23",
    colorClass: "_green",
    status: "Без статуса",
  },
  {
    id: 6,
    theme: "Research",
    title: "Название задачи",
    date: "30.10.23",
    colorClass: "_green",
    status: "Нужно сделать",
  },
  {
    id: 7,
    theme: "Research",
    title: "Название задачи",
    date: "30.10.23",
    colorClass: "_green",
    status: "В работе",
  },
  {
    id: 8,
    theme: "Copywriting",
    title: "Название задачи",
    date: "30.10.23",
    colorClass: "_purple",
    status: "В работе",
  },
  {
    id: 9,
    theme: "Web Design",
    title: "Название задачи",
    date: "30.10.23",
    colorClass: "_orange",
    status: "В работе",
  },
  {
    id: 10,
    theme: "Research",
    title: "Название задачи",
    date: "30.10.23",
    colorClass: "_green",
    status: "Тестирование",
  },
  {
    id: 11,
    theme: "Research",
    title: "Название задачи",
    date: "30.10.23",
    colorClass: "_green",
    status: "Готово",
  },
];

export const columnsFromCardList = [
  {
    id: "c1",
    title: "Без статуса",
    cards: cardList.filter((c) => c.status === "Без статуса"),
  },
  {
    id: "c2",
    title: "Нужно сделать",
    cards: cardList.filter((c) => c.status === "Нужно сделать"),
  },
  {
    id: "c3",
    title: "В работе",
    cards: cardList.filter((c) => c.status === "В работе"),
  },
  {
    id: "c4",
    title: "Тестирование",
    cards: cardList.filter((c) => c.status === "Тестирование"),
  },
  {
    id: "c5",
    title: "Готово",
    cards: cardList.filter((c) => c.status === "Готово"),
  },
];
